DATA:
  DATA_PATH: '/path/to/imagenet'
  DATASET: 'imagenet'
  IMG_SIZE: [224,224]
  INTERPOLATION: 'bicubic'
  ZIP_MODE: False
  CACHE_MODE: 'part'
  PIN_MEMORY: True
  NUM_WORKERS: 32
  BATCH_SIZE: 4

IPU:
  REPLIC: 4
  GA: 64
  DEVIterations: 1
  IPUS: 4
  PIPELINE: [2, 3, 5, 2]

TRAIN:
  START_EPOCH: 0
  EPOCHS: 300
  WARMUP_EPOCHS: 20
  WEIGHT_DECAY: 0.05
  BASE_LR: 0.001
  WARMUP_LR: 5e-7
  MIN_LR: 5e-6
  # Clip gradient norm
  CLIP_GRAD: 5.0
  # Auto resume from latest checkpoint
  AUTO_RESUME: True
  # Gradient accumulation steps
  # could be overwritten by command line argument
  ACCUMULATION_STEPS: 0
  # Whether to use gradient checkpointing to save memory
  # could be overwritten by command line argument
  USE_CHECKPOINT: False
  # LR scheduler
  LR_SCHEDULER:
    NAME: 'cosine'
    # Epoch interval to decay LR, used in StepLRScheduler
    DECAY_EPOCHS: 30
    # LR decay rate, used in StepLRScheduler
    DECAY_RATE: 0.1
  LOSS_SCALING: 1024
  # Optimizer
  OPTIMIZER:
    NAME: 'adamw'
    # Optimizer Epsilon
    EPS: 1e-8
    # Optimizer Betas
    BETAS: (0.9, 0.999)
    # SGD momentum
    MOMENTUM: 0.9

OUTPUT: '/localdata/gongboh/workspace/swin_pretrain/output/tiny_16_32/'
PRECISION: ['half','float']
AUG:
  SSL_AUG: True
  COLOR_JITTER: 0.4
  # Use AutoAugment policy. "v0" or "original"
  AUTO_AUGMENT: 'rand-m9-mstd0.5-inc1'
  # Random erase prob
  REPROB: 0.25
  # Random erase mode
  REMODE: 'pixel'
  # Random erase count
  RECOUNT: 1
  # Mixup alpha, mixup enabled if > 0
  MIXUP: 0.8
  # Cutmix alpha, cutmix enabled if > 0
  CUTMIX: 1.0
  # Cutmix min/max ratio, overrides alpha and enables cutmix if set
  CUTMIX_MINMAX: None
  # Probability of performing mixup or cutmix when either/both is enabled
  MIXUP_PROB: 1.0
  # Probability of switching to cutmix when both mixup and cutmix enabled
  MIXUP_SWITCH_PROB: 0.5
  # How to apply mixup/cutmix params. Per "batch", "pair", or "elem"
  MIXUP_MODE: 'batch'

TEST:
  CROP: True

MODEL:
  TYPE: linear
  NUM_CLASSES: 1000
  DEVICE: ipu
  NAME: swin_tiny__patch4_window7_224
  DROP_PATH_RATE: 0.0
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
